[build]
  command = "chmod +x ./build.sh && ./build.sh"
  functions = "functions"

[build.environment]
  GO_IMPORT_PATH = "github.com/BTechnopark/ipostal"
  GO111MODULE = "on"

[[redirects]]
  from = "/v1/*"
  to = "/.netlify/functions/server/:splat"
  status = 200